name: a day in Seoul
favicon: null
layout_spectrum: 0.7646877686493099
typography_spectrum: 0.17165781697258353
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7027313781436533
  lightness: 0.0015601774211972952
  saturation: 0.6359797674231231
  rhythmicContrast: 0.09979047765955329
purpose: []
